"""Initial migration

Revision ID: 0f00f3ee9518
Revises: 
Create Date: 2025-01-28 00:06:38.430516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f00f3ee9518'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flicket_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_server', sa.String(length=128), nullable=True),
    sa.Column('mail_port', sa.Integer(), nullable=True),
    sa.Column('mail_use_tls', sa.BOOLEAN(), nullable=True),
    sa.Column('mail_use_ssl', sa.BOOLEAN(), nullable=True),
    sa.Column('mail_debug', sa.BOOLEAN(), nullable=True),
    sa.Column('mail_username', sa.String(length=128), nullable=True),
    sa.Column('mail_password', sa.String(length=256), nullable=True),
    sa.Column('mail_default_sender', sa.String(length=128), nullable=True),
    sa.Column('mail_max_emails', sa.Integer(), nullable=True),
    sa.Column('mail_suppress_send', sa.BOOLEAN(), nullable=True),
    sa.Column('mail_ascii_attachments', sa.BOOLEAN(), nullable=True),
    sa.Column('posts_per_page', sa.Integer(), nullable=True),
    sa.Column('allowed_extensions', sa.String(length=256), nullable=True),
    sa.Column('ticket_upload_folder', sa.String(length=256), nullable=True),
    sa.Column('avatar_upload_folder', sa.String(length=256), nullable=True),
    sa.Column('application_title', sa.String(length=32), nullable=True),
    sa.Column('base_url', sa.String(length=128), nullable=True),
    sa.Column('auth_domain', sa.String(length=64), nullable=True),
    sa.Column('use_auth_domain', sa.BOOLEAN(), nullable=True),
    sa.Column('csv_dump_limit', sa.Integer(), nullable=True),
    sa.Column('change_category', sa.BOOLEAN(), nullable=True),
    sa.Column('change_category_only_admin_or_super_user', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=24), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('password', sa.LargeBinary(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('job_title', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=64), nullable=True),
    sa.Column('total_posts', sa.Integer(), nullable=True),
    sa.Column('total_assigned', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('flicket_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flicket_users_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_flicket_users_username'), ['username'], unique=True)

    op.create_table('flicket_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['flicket_department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_groups',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['flicket_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['flicket_users.id'], )
    )
    op.create_table('flicket_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('content', sa.String(length=5000), nullable=True),
    sa.Column('started_id', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('modified_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('assigned_id', sa.Integer(), nullable=True),
    sa.Column('ticket_priority_id', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default='2025-01-28', nullable=True),
    sa.ForeignKeyConstraint(['assigned_id'], ['flicket_users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['flicket_category.id'], ),
    sa.ForeignKeyConstraint(['modified_id'], ['flicket_users.id'], ),
    sa.ForeignKeyConstraint(['started_id'], ['flicket_users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['flicket_status.id'], ),
    sa.ForeignKeyConstraint(['ticket_priority_id'], ['flicket_priorities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flicket_topic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flicket_topic_title'), ['title'], unique=False)

    op.create_table('flicket_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=5000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('modified_id', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['modified_id'], ['flicket_users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['flicket_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['flicket_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_ticket_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['flicket_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['flicket_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('original_content', sa.String(length=5000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['flicket_post.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['flicket_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['flicket_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_ticket_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=True),
    sa.Column('data', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['flicket_post.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['flicket_users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['flicket_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['flicket_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flicket_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posts_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('original_filename', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['posts_id'], ['flicket_post.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['flicket_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flicket_uploads')
    op.drop_table('flicket_ticket_action')
    op.drop_table('flicket_history')
    op.drop_table('flicket_ticket_subscription')
    op.drop_table('flicket_post')
    with op.batch_alter_table('flicket_topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flicket_topic_title'))

    op.drop_table('flicket_topic')
    op.drop_table('flicket_groups')
    op.drop_table('flicket_category')
    with op.batch_alter_table('flicket_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flicket_users_username'))
        batch_op.drop_index(batch_op.f('ix_flicket_users_token'))

    op.drop_table('flicket_users')
    op.drop_table('flicket_status')
    op.drop_table('flicket_priorities')
    op.drop_table('flicket_group')
    op.drop_table('flicket_department')
    op.drop_table('flicket_config')
    # ### end Alembic commands ###
