"""last updated

Revision ID: 9e59e0b9d1cf
Revises: bcac6741b320
Create Date: 2020-02-14 16:11:04.280946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e59e0b9d1cf'
down_revision = 'bcac6741b320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flicket_topic', sa.Column('last_updated', sa.DateTime(), server_default='2016-11-21 17:58:26', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flicket_topic', 'last_updated')
    # ### end Alembic commands ###
