"""hours scale two dp

Revision ID: bcac6741b320
Revises: 70820003badd
Create Date: 2019-11-26 12:13:16.329436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcac6741b320'
down_revision = '70820003badd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flicket_config', 'change_category',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('flicket_config', 'change_category_only_admin_or_super_user',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('flicket_config', 'mail_ascii_attachments',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('flicket_config', 'mail_debug',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('flicket_config', 'mail_suppress_send',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('flicket_config', 'mail_use_ssl',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('flicket_config', 'mail_use_tls',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('flicket_config', 'use_auth_domain',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('flicket_post', 'hours',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('flicket_topic', 'hours',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flicket_topic', 'hours',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('flicket_post', 'hours',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('flicket_config', 'use_auth_domain',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('flicket_config', 'mail_use_tls',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('flicket_config', 'mail_use_ssl',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('flicket_config', 'mail_suppress_send',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('flicket_config', 'mail_debug',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('flicket_config', 'mail_ascii_attachments',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('flicket_config', 'change_category_only_admin_or_super_user',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('flicket_config', 'change_category',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
