"""change category config options

Revision ID: 253ae54f5788
Revises: 36c91aa9b3b5
Create Date: 2019-11-16 16:58:11.287152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253ae54f5788'
down_revision = '36c91aa9b3b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flicket_config', sa.Column('change_category', sa.BOOLEAN(), nullable=True))
    op.add_column('flicket_config', sa.Column('change_category_only_admin_or_super_user', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flicket_config', 'change_category_only_admin_or_super_user')
    op.drop_column('flicket_config', 'change_category')
    # ### end Alembic commands ###
