"""last updated

Revision ID: 9e59e0b9d1cf
Revises: bcac6741b320
Create Date: 2020-02-14 16:11:04.280946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e59e0b9d1cf'
down_revision = 'bcac6741b320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flicket_topic', sa.Column('last_updated', sa.DateTime(), server_default='2016-11-21 17:58:26', nullable=True))
    # ### end Alembic commands ###

    print("Updating last_updated dates.")

    from application import app, db
    from application.flicket.models.flicket_models import FlicketTicket, FlicketPost

    def last_update_posts(posts):

        for post in posts:
            last_updated = post.date_added

            if post.date_modified:
                last_updated = post.date_modified

        return last_updated

    query = FlicketTicket.query.all()

    update_database = False

    for ticket in query:

        last_updated = ticket.date_added

        if ticket.date_modified:
            last_updated = ticket.date_modified

        if ticket.posts:
            last_update_posts(ticket.posts)

        if ticket.last_updated != last_updated:
            update_database = True
            ticket.last_updated = last_updated

    if update_database:
        print("Commiting changes to database.")
        db.session.commit()
    else:
        # prevent thread locking of database for next migration.
        db.session.commit()
        print("No database updates required.")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flicket_topic', 'last_updated')
    # ### end Alembic commands ###

