"""hours scale two dp

Revision ID: bcac6741b320
Revises: 70820003badd
Create Date: 2019-11-26 12:13:16.329436

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bcac6741b320'
down_revision = '70820003badd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flicket_post') as batch_op:
        batch_op.alter_column('hours',
                              existing_type=sa.Numeric(precision=10, scale=0),
                              type_=sa.Numeric(precision=10, scale=2),
                              existing_nullable=True,
                              existing_server_default=sa.text("'0'"))
    with op.batch_alter_table('flicket_topic') as batch_op:
        batch_op.alter_column('hours',
                              existing_type=sa.Numeric(precision=10, scale=0),
                              type_=sa.Numeric(precision=10, scale=2),
                              existing_nullable=True,
                              existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flicket_topic', 'hours',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=0),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('flicket_post', 'hours',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=0),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
